### PR TITLE
Get rid of notifications.

### PR DESCRIPTION
**Pull request by Elronnd**
This fork is not officially endorsed by the slash'em extended development team, and the notifications are tbh kind of obnoxious.  Can you get rid of them?

### CODE REVIEW

**Comment by iology** [comment]
Sorry for disturbing you several times because of testing before. Now I just build it for tagged commits.

Do you dislike such "bot message", or need an "UNOFFICIAL" claim, or just don't want people to know this fork?

**Comment by iology** [comment]
Ok, I will control the frequency of my custom builds. If there is still any annoyance, just leave a message.

**Comment by Elronnd** [comment]
I'm fine with people knowing about the fork, but the irc messages are kind of annoying.  If you want to make an announcement, talk about it, maybe even make it official, fine, but messages don't seem very interesting.

Thanks!

**Comment by iology** [comment]
Well, I'm not a very social creature. The build script is very simple. You (the dev team?) can just copy the one here according to the license. No need for anyone other than the main developers to join and "maintain" anything.

How can I know if there are mac users lurking around for a release? I can promise only one build every 3 months or even longer (til I lost interest in this game ;-).

I'm really sorry for this.

**Comment by Elronnd** [comment]
Nothing to be sorry about!

> Well, I'm not a very social creature

How about you muster what socialness you have and join the irc channel, #em.slashem.me on freenode!

**Pull request closed without merging**
